config:
  use_colors: True

dbt_spreadsheet_transf:
  target: dev
  outputs:

    dev:
      type: postgres
      threads: 1
      host: 192.168.1.15
      port: 5432
      user: postgres
      pass: postgres
      dbname: ap_lima
      schema: common_cc

    prod:
      type: postgres
      threads: 1
      host: 192.168.1.41
      port: 5432
      user: postgres
      pass: postgres
      dbname: ap_lima
      schema: common_cc


  
